defaults:
  - _self_
  - texture_encoder: gram

username: 'cizinsky'
debug: False
output_dir: /scratch/izar/${username}/hypernca/outputs/
seed: 42

logger:
  project: hypernca
  entity: ludekcizinsky
  tags: [cs503, baseline, graph] 

data:
  trn_frac: 0.9 #0.9
  batch_size: 180 #3024
  num_workers: 20
  nca_weights_path: /scratch/izar/${username}/hypernca/pretrained_nca/Flickr+DTD_NCA
  uses_graph_encoder: True

model:
  type: 'baseline' # 'newest'
  num_weight_tokens: 5856
  temb_dim: 6
  lr: 2e-4
  weight_decay: 0.0
  warmup_epochs: 1
  warmup_factor: 0.0
  conditioning: True
  cond_dim: 256
  use_cross_attention: False
  nca_loss_every_n_steps: 0
  use_cfg: False
  cond_on_nca: False
  graph_encoder:
    hidden_dim: 96
    num_layers: 4
    dropout: 0.0
    reduce: 'mean'
    node_out_dim: 32
    edge_out_dim: 32

optim:
  max_grad_norm: 1.0
  grad_norm_type: 2.0

diffusion:
  p_mean: -1.2
  p_std: 1.8
  sigma_data: 0.5
  guidance_scale: 5.0 # 1.0 corresponds to no guidance 
  type: 'DDIM' # 'DDIM'


trainer:
  max_epochs: 600
  accelerator: gpu
  devices: 1
  checkpoint_every_n_epochs: 200
  precision: 32
  log_fid_every_n_epoch: 50


hydra:
  run:
    dir: /scratch/izar/${username}/hypernca/outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: False